spring:
  application:
    name: URL shortener

server:
  port: 9000

cassandra:
  connection:
    address: localhost
    keyspace: shortener
    port: 9042

staccato.shortener.keyLength: 7


---
spring:
   profiles: docker
   application:
      name: URL shortener
server:
   port: 9000
cassandra:
  connection:
    address: cassandra

---
spring:
   profiles: staging
   application:
      name: URL shortener
server:
   port: 8080
